name: CI - ms-carrito

on:
  push:
    branches:
      - main
      - pruebas-aws
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # Volvemos a tu carpeta raíz ms_carrito
        working-directory: ms_carrito 

    steps:
      - name: Descargar código
        uses: actions/checkout@v4 

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Respetando el Java 17 de tu stack técnico
          cache: 'maven'

      - name: Dar permisos al wrapper
        run: chmod +x ./mvnw 

      - name: Compilar proyecto
        run: ./mvnw clean package -DskipTests

      - name: Construir imagen Docker
        # Si falla el nombre estándar, le obligamos a buscar el archivo en la ruta actual
        run: |
          if [ -f ./Dockerfile ]; then
            docker build -f ./Dockerfile -t ms-carrito .
          elif [ -f ./dockerfile ]; then
            docker build -f ./dockerfile -t ms-carrito .
          else
            echo "❌ ERROR: No se encontró ningún archivo Dockerfile o dockerfile en la carpeta ms_carrito"
            ls -la
            exit 1
          fi